spring:
  application:
    name: course-gateway
  # 路由转发配置
  cloud:
    gateway:
      routes:
      - id: system
        uri: http://127.0.0.1:7001
        predicates:
        - Path=/system/**

server:
  port: 9000

eureka:
  # 声明Eureka客户端需要注册到的服务端的地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

