spring:
  application:
    name: course-system

server:
  port: 7001
  # 请求访问上下文
  servlet:
    context-path: /system

eureka:
  # 声明Eureka客户端需要注册到的服务端的地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/