spring:
  application:
    name: course-system
  datasource:
    url: jdbc:mysql://114.115.175.199:3306/course?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: LTAI2cUh4boM8E2f@
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 7001
  # 请求访问上下文
  servlet:
    context-path: /system

eureka:
  # 声明Eureka客户端需要注册到的服务端的地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 指明mapper对应的XML文件的地址
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# 开启MyBatis的日志打印
logging:
  level:
    #打印SQL信息  日志打印的级别不同
    com.liugaoyang.course.system.mapper: DEBUG