spring:
  application:
    name: course-eureka-server
server:
  port: 8761

eureka:
  # 实例
  instance:
    hostname: localhost
  client:
    # 是否从其他Eureka server中获取注册信息 默认是true
    # 单节点的Eureka Server 不需要从其他节点获取注册信息
    fetch-registry: false
    # 是否将自己注册到 Eureka Server上默认为true
    register-with-eureka: false
    # 设置EurekaServer 所在的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/